= Gitea Podman Install Guide
:author:    Antonio C.
:email:     <sp38af (at) trikorasolutions (dot) com>
:toc: left
:toc-leves: 3
:icons: font
:Description: Gitea Podman Install Guide

== Preparation

Define the following variables.

[source,bash]
----
PGSQL_PW
----

== Deployment

Create the podman volumes that will store the database and gitea web application data.

[source,bash]
----
podman volume create gitea_db_data --label "name=gitea_db_data,component=pv,part-of=gitea"
podman volume create gitea_data --label "name=gitea_data,component=pv,part-of=gitea"
podman volume create gitea_config --label "name=gitea_config,component=pv,part-of=gitea"
----

Create the `gitea` POD that will hold the gitea application and resources. 

[NOTE]
====
The only port that will be mapped, in this document, is `8069` which is the default
gitea web application port. If required the database port could also be published
by adding extra `-p` parameters.
====

[source,bash]
----
podman pod create --name gitea -p 13300:80 -p 13322:22 -p 13432:5432 --label "name=gitea"
----

Start the PostgreSQL database container inside the `gitea`.

[TIP]
====
The `-d` switch will run the container in detached mode. 
====

[source,bash]
----
podman run --name gitea_pgsql --pod gitea -d -v "gitea_db_data:/var/lib/postgresql/data/pgdata:Z" -e POSTGRES_DB=gitea -e POSTGRES_USER=gitea -e POSTGRES_PASSWORD=${PGSQL_PW} -e "PGDATA=/var/lib/postgresql/data/pgdata"  --label "name=postgresql,component=database,part-of=gitea" postgres:14
----

Start the gitea container inside the `gitea` pod.

[NOTE]
====
The `--privileged` switch is used to fix the *Permission denied when restoring a database* problem.
====

[source,bash]
----
podman run --name gitea_web --privileged --pod gitea -d -v "gitea_data:/var/lib/gitea:z" -v "gitea_config:/etc/gitea:Z"  -v "gitea_web_addons:/mnt/extra-addons:Z" 
-e USER_UID=1000 -e USER_GID=1000 -e GITEA__database__DB_TYPE=postgres -e GITEA__database__HOST=db:5432 -e GITEA__database__NAME=gitea -e GITEA__database__USER=gitea -e GITEA__database__PASSWD=${PGSQL_PW} --label "name=gitea,component=web,part-of=gitea" gitea/gitea:1.18.5
----

== Uninstall

Stop the pods.

[source,bash]
----
podman pod stop gitea
----

Remove the podman pod with everything inside.

[source,bash]
----
podman pod rm -f gitea
----

Remove the local folders.

[source,bash]
----
rm -Rf /z/var/lib/gitea_volumes
----

Remove the podman volumes.

Create the podman volumes that will store the database and gitea web application data.

[source,bash]
----
podman volume rm gitea_db_data gitea_data gitea_config
----
