= Kubernetes 1.33
:toc:       left
:toc-title: Table of Contents
:icons: font
:source-highlighter: highlight.js
:description: Kubernetes 1.33 installation guide

== Install on Fedora Server 42

References: 

* https://docs.fedoraproject.org/en-US/quick-docs/using-kubernetes-kubeadm/
* https://computingforgeeks.com/join-new-kubernetes-worker-node-to-existing-cluster/

=== Specs

Control Plane

vCPU: 4 core
RAM: 8 GB
HD: 120GB

Compute Nodes

vCPU: 8 core
RAM: 16 GB
HD: 200GB


=== Install


[source,bash]
----
sudo dnf update
----


[source,bash]
----
sudo systemctl stop swap-create@zram0
sudo dnf remove zram-generator-defaults
sudo reboot now
----

[source,bash]
----
sudo systemctl disable --now firewalld
sudo dnf install -y iptables iproute-tc
----


[source,bash]
----
sudo cat <<EOF | sudo tee /etc/modules-load.d/k8s.conf
overlay
br_netfilter
EOF
----


[source,bash]
----
sudo cat <<EOF | sudo tee /etc/sysctl.d/k8s.conf
net.bridge.bridge-nf-call-iptables  = 1
net.bridge.bridge-nf-call-ip6tables = 1
net.ipv4.ip_forward                 = 1
EOF
----

[source,bash]
----
sudo sysctl --system
sudo reboot now
----

Verify

[source,bash]
----
lsmod | grep br_netfilter
lsmod | grep overlay
----

[source,bash]
----
sysctl net.bridge.bridge-nf-call-iptables net.bridge.bridge-nf-call-ip6tables net.ipv4.ip_forward
----

[source,bash]
----
sudo dnf install -y cri-o1.33 containernetworking-plugins
----

[source,bash]
----
sudo dnf list kubernetes1.33
----

[source,bash]
----
sudo dnf install -y kubernetes1.33 kubernetes1.33-kubeadm kubernetes1.33-client
----

[source,bash]
----
sudo systemctl enable --now crio
----

[source,bash]
----
sudo kubeadm config images pull
----

=== Initialize cluster

Initialize the cluster or join an existing cluster.

[source,bash]
----
sudo kubeadm init --pod-network-cidr=10.244.0.0/16
----

==== Join an existing cluster

Get the token.

[source,bash]
----
$ kubeadm token list
TOKEN                     TTL         EXPIRES                USAGES                   DESCRIPTION                                                EXTRA GROUPS
yyyyyy.xxxxxxxxxxxxxxxx   6h          2025-08-31T21:18:33Z   authentication,signing   The default bootstrap token generated by 'kubeadm init'.   system:bootstrappers:kubeadm:default-node-token
----

sudo kubeadm join 192.168.1.10:6443 --token yyyyyy.xxxxxxxxxxxxxxxx  --discovery-token-ca-cert-hash sha256:zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz 

=== Taint nodes

==== Control plane

kubectl taint nodes k8sprdcp1 node-role.kubernetes.io/control-plane:NoSchedule
kubectl taint nodes k8sprdcp2 node-role.kubernetes.io/control-plane:NoSchedule

==== Worker node

kubectl label node k8sprdwrk1 node-role.kubernetes.io/worker=worker

Remove Control plane.

kubectl label node k8sprdwrk1.trikorasolutions.net node-role.kubernetes.io/worker-

=== Lock the Kubernetes major.minor version

[source,bash]
----
sudo dnf versionlock add kubernetes*-1.33.* cri-o-1.33.*
----

== Ingress

[source,bash]
----
kubectl apply -f https://kind.sigs.k8s.io/examples/ingress/deploy-ingress-nginx.yaml
----

== Load Balancer

[source,bash]
----
kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/v0.15.2/config/manifests/metallb-native.yaml
----

[source,bash]
----
kubectl apply -f kubernetes/k8s-1.33/metallb.yaml
----