= Ceph Storage on Kubernetes
:toc:       left
:toc-title: Table of Contents
:icons: font
:description: Ceph Storage on Kubernetes
:source-highlighter: highlight.js

== Intruduction

[.lead]
This section describes deploying Ceph storage on Kubernetes.

== Create Ceph Pool

Create Ceph pool for Kubernetes & client key

[sourec,bash]
----
ansible-playbook kubernetes/storage/ceph/ansible/60-proxmox-create-cephfs-pool.yaml \
  -e @kubernetes/storage/ceph/ansible/defaults/main.yaml \
  -e proxmox_host=${PROXMOX_HOST}
----

== Collect information

Define environment variables.

[source,bash]
----
CEPH_ADM_KEY=<1>
PROXMOX_HOST=<2>
----
<1> Ceph Admin Key obtained with `ceph auth get-key client.admin` using root.
<2> Ansible inventory hostname for a proxmox host.

== Using Ceph

Add the https://ceph.github.io/csi-charts helm repository.

[sourec,bash]
----
helm repo add ceph-csi https://ceph.github.io/csi-charts
----

[sourec,bash]
----
ansible-playbook kubernetes/storage/ceph/ansible/05-setup-ceph-csi-cephfs.yaml \
  -e @kubernetes/storage/ceph/ansible/defaults/main.yaml \
  -e ceph_admin_key=${CEPH_ADM_KEY}
----

[sourec,bash]
----
ansible-playbook kubernetes/storage/ceph/ansible/09-remove-ceph-csi-cephfs.yaml \
  -e @kubernetes/storage/ceph/ansible/defaults/main.yaml
----

== Configure Ceph OSD

The following instructions and scripts were generated with information 
 obtained from 
 link:https://computingforgeeks.com/ceph-persistent-storage-for-kubernetes-with-cephfs/[computingforgeeks - Ceph Persistent Storage for Kubernetes with Cephfs] 
 and link:https://computingforgeeks.com/persistent-storage-for-kubernetes-with-ceph-rbd/[computingforgeeks - Persistent Storage for Kubernetes with Ceph RBD]
 tutorials.

[sourec,bash]
----
ansible-playbook kubernetes/storage/ceph/ansible/55-setup-cephfs.yaml \
  -e @kubernetes/storage/ceph/ansible/defaults/main.yaml \
  -e ceph_admin_key=${CEPH_ADM_KEY}
----

Set the `ceph_monitors` variable with the list of Ceph Monitor information, 
 e.g. `10.10.10.11:6789,10.10.10.12:6789,10.10.10.13:6789`. It can be provided 
 to the following playbook as part of the `_local_config/network.yaml` file.

[sourec,bash]
----
ansible-playbook kubernetes/storage/ceph/ansible/65-setup-cephfs.yaml \
  -e @kubernetes/storage/ceph/ansible/defaults/main.yaml \
  -e @_local_config/network.yaml
----

[sourec,bash]
----
ansible-playbook kubernetes/storage/ceph/ansible/90-test-cephfs.yaml \
  -e @kubernetes/storage/ceph/ansible/defaults/main.yaml
----

== Uninstall

[sourec,bash]
----
ansible-playbook kubernetes/storage/ceph/ansible/99-uninstall.yaml \
  -e @kubernetes/storage/ceph/ansible/defaults/main.yaml
----

== Configure Ceph RBD

TBD


== References

* https://docs.ceph.com/en/latest/rbd/rbd-kubernetes/
* https://computingforgeeks.com/ceph-persistent-storage-for-kubernetes-with-cephfs/
* https://www.digitalocean.com/community/tutorials/how-to-set-up-a-ceph-cluster-within-kubernetes-using-rook