glpi_agent_version: 1.17

# https://github.com/glpi-project/glpi-agent/releases/download/1.17/glpi-agent-1.17-linux-installer.pl
# https://github.com/glpi-project/glpi-agent/releases/download/1.17/glpi-agent-1.17-x86_64.AppImage
# https://github.com/glpi-project/glpi-agent/releases/download/1.17/glpi-agent-1.17-1.noarch.rpm
# https://github.com/glpi-project/glpi-agent/releases/download/1.17/glpi-agent_1.17-1_all.deb
