= GLPI AWX Execution Environment
Antonio C. <sp38af (at) trikorasolutions (dot) com>
:icons: font
:revdate: {docdate}
:stem: latexmath
:toc: left
:toclevels: 3
:toc-title: Table of Contents
:description: Build process for the GLPI AWX execution environment.

== Create Execution Environment

Files required for building an Execution Enviromnent.

* `execution-environment.yml`: Execution Environment definition
* `bindep.txt`: System dependencies
* `requirements.txt`: Python requiremends
* `requirements.yml`: Ansible requirements

.Default `bindep.txt` - https://github.com/ansible/awx-ee/blob/devel/_build/bindep.txt  
[source]
----
python38-devel [platform:rpm compile]
subversion [platform:rpm]
subversion [platform:dpkg]
git-lfs [platform:rpm]
----

.Default `requirements.txt` - https://github.com/ansible/awx-ee/blob/devel/_build/requirements.txt
[source]
----
git+https://github.com/ansible/ansible-sign
ansible-runner>=2.3.1
----

.Default requirements.yml - https://github.com/ansible/awx-ee/blob/devel/_build/requirements.yml
[source, yaml]
----
---
collections:
  - name: awx.awx
  - name: azure.azcollection
  - name: amazon.aws
  - name: theforeman.foreman
  - name: google.cloud
  - name: openstack.cloud
  - name: community.vmware
  - name: ovirt.ovirt
  - name: kubernetes.core
  - name: ansible.posix
  - name: ansible.windows
  - name: redhatinsights.insights
...
----


=== GLPI

[NOTE]
====
`podman` can be replaced by `docker` as `container-runtime`. Check the `ansible-builder build --help`.
====

[CAUTION]
====
Replace `xxxxxxxx` with the quay user/organization.
====


[source,bash]
----
$ ansible-builder build --tag xxxxxxxx/awx-ee-glpi:0.0.1 --container-runtime podman --file awx/config/execution-environment/glpi/execution-environment.yml --context contexts/glpi/
Running command:
  podman build -f context/Containerfile -t xxxxxxxx/awx-ee-glpi:0.0.1 context
Complete! The build context can be found at: /mnt/e/Projekte/Ansible/awx-ee/context
----

[source,bash]
----
$ podman image ls | grep ee
REPOSITORY                                   TAG                  IMAGE ID      CREATED         SIZE
localhost/xxxxxxxx/awx-ee-glpi          0.0.1                0dfd4e306b8a  5 minutes ago   1.1 GB
----

=== Push the image to Quay.io

Login into [quay.io](https://quay.io/).

[source,bash]
----
$ buildah login quay.io
Username: xxxxxxx
Password: 
Login Succeeded!
----

Push the image tag to [quay.io](https://quay.io/).

[source,bash]
----
$ buildah images
REPOSITORY                                    TAG                   IMAGE ID       CREATED          SIZE
localhost/xxxxxxxx/awx-ee-glpi           0.0.1                 0dfd4e306b8a   4 minutes ago    1.1 GB
----

[source,bash]
----
$ buildah push localhost/xxxxxxxx/awx-ee-glpi:0.0.1 docker://quay.io/trikorasolns/awx-ee-glpi:0.0.1
----

If the `push` succeeds the output should end with:

[source,bash]
----
Writing manifest to image destination
Storing signatures
----

And the container will be available at https://quay.io/repository/trikorasolns/awx-ee-glpi.

[NOTE]
====
To also tag the image as the `latest` image to:

[source,bash]
----
$ buildah push localhost/xxxxxxxx/awx-ee-glpi:0.0.1 docker://quay.io/trikorasolns/awx-ee-glpi:latest
----

====

== Troubleshooting

=== Error creating pod: container failed to start, ImagePullBackOff

*Problem*

Error creating pod: container failed to start, ImagePullBackOff

*Symptoms*

[source,bash]
----
$ kubectl -n awx get all
NAME                                                   READY   STATUS         RESTARTS       AGE
pod/automation-job-28-cftwg                            0/1     ErrImagePull   0              34s
----

[source,bash]
----
$ kubectl -n awx describe pod/automation-job-28-cftwg
...
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  21s               default-scheduler  Successfully assigned awx/automation-job-28-cftwg to awx.localdomain
  Normal   BackOff    16s               kubelet            Back-off pulling image "quay.io/trikorasolns/awx-ee-glpi:latest"
  Warning  Failed     16s               kubelet            Error: ImagePullBackOff
  Normal   Pulling    4s (x2 over 19s)  kubelet            Pulling image "quay.io/trikorasolns/awx-ee-glpi:latest"
  Warning  Failed     3s (x2 over 17s)  kubelet            Failed to pull image "quay.io/trikorasolns/awx-ee-glpi:latest": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/trikorasolns/awx-ee-glpi:latest not found: manifest unknown: manifest unknown
  Warning  Failed     3s (x2 over 17s)  kubelet            Error: ErrImagePull
----

*Cause*

The `latest` tag doesn't exist.

*Solution*

Either push the image as the `latest` tag or replace with the correct version.


== References

* https://thedatabaseme.de/2022/09/09/self-build-awx-execution-environment/
