= Gitea Deployment Guide with Helm
:author:    Antonio C.
:email:     <sp38af (at) trikorasolutions (dot) com>
// :Date:      20210222
:revdate: {docdate}
:toc:       left
:toclevels: 3
:toc-title: Table of Contents
:icons: font
:description: This document describes the k8s installation process for Gitea using Helm.

== Implement

Password

== Prepare

[.lead]
Prepare the environment.

Create the namespace.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-prepare-playbook.yaml \
  -e "@gitea/k8s/ansible/defaults/main.yaml"
----

Create HostPath PVs and their supporting folders.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-prepare-playbook.yaml -K \
  -e "@gitea/k8s/ansible/defaults/main.yaml"
----

2 PV will be created, one for the database and the other for the application.

[source,bash]
----
kubectl get pv
----

[source,]
----
NAME                    CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                STORAGECLASS 
gitea-gitea-data-pv     30Gi       RWO            Retain           Available   gitea/gitea-data     local-storage
gitea-postgresql-pv     10Gi       RWO            Retain           Available   gitea/postgresql     local-storage
----

Cleanup preparation.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-cleanup-playbook.yaml -K \
  -e "@gitea/k8s/ansible/defaults/main.yaml"
----

== Install

=== PostgreSQL

Deploy the postgreSQL database by checking the 
  link:../../../pgsql/k8s/helm/README.adoc[PostgreSQL README] instructions
  adding the `custom_helm_values_file`  parameter to the gitea custom helm 
  values.

=== PostgreSQL

Install PostgreSQL using the Helm Chart.

[source,bash]
----
ansible-playbook pgsql/k8s/helm/ansible/pgsql-install-playbook.yaml \
  -e "@gitea/k8s/ansible/defaults/main.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD}
----

Get information from the service.

[source,bash]
----
kubectl -n gitea get pod postgres-0
----

[source,]
----
NAME           READY   STATUS    RESTARTS   AGE
postgresql-0   1/1     Running   0          3m29s
----

[source,bash]
----
kubectl -n gitlab get svc
----

[source,]
----
NAME         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)    AGE
postgresql   ClusterIP   10.111.102.121   <none>        5432/TCP   4m48s
----

=== Gitea

[source,bash]
----
ansible-playbook gitea/k8s/helm/ansible/gitea-install-playbook.yaml \
  -e "@gitea/k8s/ansible/defaults/main.yaml" \
  -e "@_local_config/network.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD} 
----

=== Uninstall

Use the following playbook command to uninstall the helm chart.

[source,bash]
----

----

Don't forget to check and eventually patch the _Released_ PVs.

[source,bash]
----
kubectl get pv
----

[source,bash]
----
NAME                             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS
gitlab-gitlab-etc-local-pv       5Gi        RWO            Retain           Released
gitlab-gitlab-var-log-local-pv   5Gi        RWO            Retain           Released
gitlab-gitlab-var-opt-local-pv   20Gi       RWO            Retain           Released
----

Or completely remove everything.

[NOTE]
====
The persistence information is provided in the 
 link:ansible/default/main.yaml[] file.
====

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-cleanup-playbook.yaml -K \
  -e "@gitea/k8s/ansible/defaults/main.yaml"
----
