= Odoo 13 -> 14 Upgrade Guide
Antonio C. <sp38af (at) trikorasolutions (dot) com>
:toc: left
:revdate: {docdate}
:icons: font
:Description: Guide for deploying Odoo from 13 to 14 as a podman container.

== Upgrade

[.lead]
Upgrade instructions.

=== Requirements

All upgrades require an export file with the database on the starting version.


== 13.0 -> 14.0

[.lead]
Upgrade from `13.0` to `14.0`.

*References*: 

* https://oca.github.io/OpenUpgrade/coverage_analysis/modules130-140.html
* https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/README.rst


=== Start the target container

Stop de odoo 13 container and delete it.

[source,bash]
----
podman stop odoo_web
podman rm odoo_web
----

Start the odoo 14 container.

[source,bash]
----
podman run -it --name odoo_web --privileged --pod odoo -v "odoo_web_data:/var/lib/odoo:z" -v "odoo_web_configs:/etc/odoo:Z"  -v "odoo_web_addons:/mnt/extra-addons:Z" -e POSTGRES_DB=postgres -e USER=odoo -e PASSWORD=1234  -e HOST=odoo_pgsql -e USER=odoo  --label "name=odoo,component=web,part-of=odoo" odoo:14.0 /bin/bash
----

=== Configure starting environment

Install odoo on the starting version, restore the database and start the pod.

Clone the _OpenUpgrade_ GitHub project.

[source,bash]
----
git clone --branch=14.0 --depth=1 --single-branch git@github.com:OCA/OpenUpgrade.git OpenUpgrade-14.0
git clone --depth=1 --single-branch https://github.com/OCA/openupgradelib.git
----

Copy the 2 addon folders to the container under the `/mnt/extra-addons/` folder.

[source,bash]
----
podman cp OpenUpgrade/openupgrade_scripts/ odoo_web:/mnt/extra-addons/
podman cp OpenUpgrade/openupgrade_framework/ odoo_web:/mnt/extra-addons/
----
 
Check the <<openupgradelib,openupgradelib>> section to make sure this Python library is installed. The Python version for Odoo 14.0 is Python 3.7.


==== Add the `openupgrade_scripts` to the odoo installation

Adding the upgrade addon to the installation is done with the `odoo.conf` file.

Download the file.

[source,bash]
----
podman cp odoo_web:/etc/odoo/odoo.conf ./odoo.upg.conf
----

Edit the file `` and add database configuration properties.

[source,]
----
db_host = odoo_pgsql
db_port = 5432
db_user = odoo
db_password = 1234
----

[NOTE]
====
Tthe `upgrade_path` configuration, which probably doesn't exist, pointing to the copied `openupgrade_scripts` subfolder.

[source,]
----
upgrade_path = /mnt/extra-addons/openupgrade_scripts/
server_wide_modules = web,openupgrade_framework
----
====

Save the file and push it into the odoo container.

[source,bash]
----
podman cp odoo.upg.conf odoo_web:/etc/odoo/
----

=== Execute the upgrade

Execute the upgrade by checking the <<execute_the_upgrade,Execute the upgrade>> section.

=== Start the new Odoo version

Before starting the odoo container remove the one used by the upgrade.



[source,bash]
----
podman run --name odoo_web --privileged --pod odoo -d -v "odoo_web_data:/var/lib/odoo:z" -v "odoo_web_configs:/etc/odoo:Z"  -v "odoo_web_addons:/mnt/extra-addons:Z" -e POSTGRES_DB=postgres -e USER=odoo -e PASSWORD=1234  -e HOST=odoo_pgsql -e USER=odoo  --label "name=odoo,component=web,part-of=odoo" odoo:14.0
----
