= Deploy PostgreSQL on Kubernetes
:author:    Antonio C.
:email:     <ac (at) trikorasolutions (dot) com>
:revdate:   {{docdate}}
:toc:       left
:toc-title: Table of Contents
:icons:     font
:description: Deploy PostgreSQL on a Kubernetes cluster
:source-highlighter: highlight.js

== Introduction

[.lead]
This document describes having PostgreSQL deployed on a Kubernetes cluster using Helm.

== Preparation

TBD

== Playbooks

=== PostgreSQL Install Playbook

[.lead]
Playbook that deploys the Apache Superset application.

*Parameters*

.PostgreSQL install playbook parameters.
[cols="20%,80%"]
|===
|Field name |Description

| `app_namespace`

[.fuchsia]#string# / [.red]#required# 

a| Namespace where the database will be deployedinto.

| `db_image_tag`

[.fuchsia]#string#

a| Database image tag

[.blue]#*Default: 16*#

| `db_name`

[.fuchsia]#string# / [.red]#required# 

a| Database name

| `db_user`

[.fuchsia]#string# / [.red]#required# 

a| Database user name

| `db_password`

[.fuchsia]#string# / [.red]#required# 

a| Database user password

| `pgsql_image_repo`

[.fuchsia]#string#

a| Image repository for PostgreSQL

Examples:

* [.blue]#*Default: postgres*#
* registry.redhat.io/rhel8/postgresql-16 (for OpenShift)

| `pgsql_image_tag`

[.fuchsia]#string#

a| Tag for the Image repository provided in the `pgsql_image_repo` parameter.

[.blue]#*Default: latest*#

| `storageClassName`

[.fuchsia]#string# 

a| Storage class used to persist the database into.

If not informed it will default to the kubernetes default storage class.

| `trikora_helm_project_dir`

[.fuchsia]#path#

a| Local location for the Trikora Helm GitHub project.

|===

[source,bash]
----
ansible-playbook pgsql/k8s/helm/ansible/pgsql-install-playbook.yaml \
  -e "@kubernetes/storage/<storage>/ansible/defaults/main.yaml" \
  -e "@<app>/k8s/ansible/defaults/main.yaml" \
  -e db_password=${DB_PASSWORD}
----

=== PostgreSQL Uninstall Playbook

*Parameters*

.PostgreSQL uninstall parameters.
[cols="20%,80%"]
|===
|Field name |Description

| `app_namespace`

[.fuchsia]#string# / [.red]#required# 

a| Namespace where the database will be deployed into.

| `trikora_helm_project_dir`

[.fuchsia]#path#

a| Local location for the Trikora Helm GitHub project.

|===


[source,bash]
----
ansible-playbook pgsql/k8s/helm/ansible/pgsql-uninstall-playbook.yaml -e "@gitea/k8s/gitea_variables.yaml"   -e trikora_helm_project_dir=${TRIKORA_HELM}
----

== Upgrade


== Manual operations

=== Manual deployment

Template the helm file.

[source,bash]
----
jinja2 --format=yaml -DDB_PASSWORD=${DB_PASSWORD} -DAPP_NAME=${APP_NAME} pgsql/k8s/helm/helm-pgsql-values.yaml.j2 > /tmp/helm-pgsql-values.yaml
----

[source,bash]
----
helm upgrade --install --namespace ${APP_NAME} -f /tmp/helm-odoo-odoo-values.yaml odoo ${HELM_CHART_FOLDER:-.}/postgresql
----

[source,bash]
----
ansible-playbook pgsql/k8s/helm/ansible/pgsql-install-playbook.yaml \
  -e app_name=${APP_NAME} \
  -e app_version=${APP_VERSION} \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e app_namespace=${APP_NAME} \
  -e db_password=${DB_PASSWORD} \
  -e db_name=${DB_PASSWORD} \
  -e db_user=${APP_NAME} \
  -e db_image_tag=13

  -e k8s_host=${KUBERNETES_NODE_NAME} \

----

Use the application variables file.

[source,bash]
----
ansible-playbook pgsql/k8s/helm/ansible/pgsql-install-playbook.yaml \
  -e "@gitea/k8s/gitea_variables.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD} \
  -e db_image_tag=13 \
  -e iscsi_portal=${ISCSI_PORTAL} \
  -e iscsi_target=${ISCSI_TARGET}
----