= Odoo install with Helm
:author:      Antonio C.
:email:       <sp38af (at) trikorasolutions (dot) com>
:revdate:     {docdate}
:toc:         left
:toc-title:   Table of Contents
:icons:       font
:description: Odoo Deployment Guide Helm edition.


== Prepare

This task will:

* create the application namespace
* create the folders that will support the local pv
* create the pv

=== Set environment variables

The installation process requires setting the following environment variables.

[source,bash]
----
K8S_HOST=kuberneteshost
DB_PASSWORD=admin123
ODOO_VERSION=18
----


=== Create kubernetes namespace

[.lead]
Create the PV and it's FS folders on the kubernetes node.

This task will be performed by Ansible.

Create the namespace.

[source,bash]
----
ansible-playbook kubernetes/ansible/host_path/app-prepare-playbook.yaml \
  -e "@odoo/k8s/ansible/defaults/main.yaml" \
  -e "@odoo/k8s/ansible/defaults/odoo-${ODOO_VERSION}.yaml"
----

=== Prepare PV

Create HostPath PVs and their supporting folders.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-prepare-playbook.yaml -K \
  -e "@odoo/k8s/ansible/defaults/main.yaml" \
  -e "@odoo/k8s/ansible/defaults/odoo-${ODOO_VERSION}.yaml"
----


== Install

[WARNING]
====
The name of the database must be `postgres`.
====

=== PostgreSQL

Install PostgreSQL using the Helm Chart.

[source,bash]
----
ansible-playbook pgsql/k8s/helm/ansible/pgsql-install-playbook.yaml \
  -e "@odoo/k8s/ansible/defaults/main.yaml" \
  -e "@odoo/k8s/ansible/defaults/odoo-${ODOO_VERSION}.yaml" \
  -e db_image_tag=13 \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD}
----

=== Odoo

Install Odoo using the Helm Chart.

[source,bash]
----
ansible-playbook odoo/k8s/ansible/odoo-install-playbook.yaml \
  -e "@odoo/k8s/ansible/defaults/main.yaml" \
  -e "@odoo/k8s/ansible/defaults/odoo-${ODOO_VERSION}.yaml" \
  -e "@_local_config/network.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD} 
----

== Uninstall 

=== Odoo

Uninstall Odoo.

[source,bash]
----
ansible-playbook odoo/k8s/ansible/pb-uninstall.yaml \
  -e app_name=${APP_NAME} \
  -e app_version=${APP_VERSION} \
  -e app_namespace=${APP_NAME}
----

Cleanup all Odoo installation.

[source,bash]
----
ansible-playbook -K odoo/k8s/ansible/pb-uninstall-cleanup.yaml \
  -e app_name=${APP_NAME} \
  -e app_version=${APP_VERSION} \
  -e app_namespace=${APP_NAME}
----

=== Uninstall PostgreSQL

Uninstall PostgreSQL.

[source,bash]
----
ansible-playbook pgsql/k8s/helm/ansible/pgsql-uninstall-playbook.yaml \
  -e "@odoo/k8s/ansible/defaults/main.yaml" \
  -e "@odoo/k8s/ansible/defaults/odoo-${ODOO_VERSION}.yaml" \
  -e db_image_tag=13 \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD}
----

If required patch the PV to clear the PVC reference.

[source,bash]
----
kubectl patch pv odoo-${ODOO_VERSION}-postgresql-pv -p '{"spec":{"claimRef": null}}'
----

== Remove PV

Remove the references to the PVs.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-cleanup-playbook.yaml -K \
  -e "@odoo/k8s/ansible/defaults/main.yaml" \
  -e "@odoo/k8s/ansible/defaults/odoo-${ODOO_VERSION}.yaml"
----

