= OCP on UPI RHOSP
Antonio C. <ac (at) trikorasolutions (dot) com>
:revdate: {docdate}
:icons: font
:toc: left
:toclevels: 3
:toc-title: Table of Contents
:description: OCP UPI Installation on Proxmox

== Introduction

[.lead]
This document describes the installation process for deploying OCP on a UOI 
 RHOSP platform.

== Prepare

Check the generic 
 link:../README.adoc#collect-information[Collect Information] 
 section.


== Install

[.lead]
Generate OCP Cluster installation folder and download the OCP binaries.

This will generate a directory with name defined on the `ocp_install_root_dir`
 variable. This directory will be placed under the `ansible_user` home 
 directory if the `ocp_install_root_dir_under_user_home` variable is true.

[source,bash]
----
ansible-playbook ocp/4.15/ansible/02-ocp-services-oi-binaries.yaml \
  -e @ocp/4.15/ansible/defaults/main.yaml \
  -e ocp_cluster_name=ocponrhosp
----


[.lead]
Generate the _OpenShift Cluster_ installation directory and generate the 
 Kubernetes manifests and Ignition configuration files for the cluster.

This is done using the `openshift-install` CLI.

[source,bash]
----
ansible-playbook ocp/4.15/ansible/18-ocp-services-oi-playbook.yaml \
  -e @ocp/4.15/ansible/defaults/main.yaml \
  -e @_local_config/network.yaml \
  -e pull_secret=${RH_CLUSTER_PULL_SECRET} \
  -e ssh_pub_key_file=${SSH_PUB_KEY_FILE} \
  -e ocp_cluster_name=${OCP_CLUSTER_NAME}
----

Import openshift image to openstack.

OCP_CLUSTER_NAME="ovhcpococp"
OPENSTACK_NETWORK="openshift"
OPENSTACK_KEYPAIR="poc_openshift_trikorasolns"
OPENSTACK_FLAVOR="b3-8"
INSTANCE_NAME="ocp_poc_trikora"

openstack  --os-region-name GRA11 image create --container-format=bare --disk-format=qcow2 --file /z/_dw/rhcos-415.92.202407091355-0-openstack.x86_64.qcow2 rhcos-${OCP_CLUSTER_NAME}

openstack server create             \
  --os-region-name GRA11            \
  --key-name="${OPENSTACK_KEYPAIR}" \
  --network=$OPENSTACK_NETWORK      \
  --flavor=$OPENSTACK_FLAVOR        \
  --image="${IMAGE}"                \
  --user-data ./_local_config/ovhcpococp/bootstrap.ign \
  "${INSTANCE_NAME}"

openstack --os-region-name GRA11 image list

== References

* https://docs.redhat.com/en/documentation/openshift_container_platform/4.11/html/installing/installing-on-openstack
* https://docs.redhat.com/en/documentation/openshift_container_platform/4.11/html/installing/installing-on-openstack#cluster-entitlements_installing-openstack-user
* https://github.com/openshift/installer/tree/release-4.15/upi/openstack
* https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-openstack/
* https://github.com/openshift/installer/blob/main/docs/user/openstack/install_upi.md
