---
- name: "Install PostgreSQL - {{ db_image_tag }}"
  hosts: "{{ k8s_host | default(ocp_bastion) | default('ocp_bastion') | default('localhost') }}"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  pre_tasks:
    - name: "Validate variables"
      assert:
        that:
          - "app_namespace is defined and (app_namespace | length > 0)"
          - "db_password is defined and (db_password | length > 0)"
          - "db_name is defined and (db_name | length > 0)"
          - "db_user is defined and (db_user | length > 0)"
        fail_msg: "Missing variables"

  tasks:
    - name: "Template PostgreSQL Helm values file"
      ansible.builtin.template:
        src: "{% if custom_helm_values_file is defined and (custom_helm_values_file | length > 0) %}{{ custom_helm_values_file }}{% else %}helm-pgsql-values.yaml.j2{% endif %}"
        dest: "/tmp/helm-pgsql-values.yaml"
        mode: '0600'

    - name: "Deploy PostgreSQL with deployed Helm chart"
      kubernetes.core.helm:
        name: postgresql
        chart_ref: "{% if trikora_helm_project_dir is defined %}{{ trikora_helm_project_dir }}/charts/postgresql{% else %}trikorasolns/postgresql{% endif %}"
        release_namespace: "{{ app_namespace }}"
        wait: true
        replace: false
        values_files:
          - files/helm-pgsql-values.yaml
          - /tmp/helm-pgsql-values.yaml
      register: pgsql_helm_install_res 

    - name: "Print installation result"
      ansible.builtin.debug:
        var: pgsql_helm_install_res

    - name: "Delete template file"
      ansible.builtin.file:
        path: /tmp/helm-pgsql-values.yaml
        state: absent
...
