= GLPI Podman Deployment Guide
:author:    A. Costa
:email:     <a dot costa at trikorasolutions dot com>
:Date:      2022/05/02
:Revision:  1
:toc:       left
:toc-title: Table of Contents
:icons: font
:description: This section describes the GLPI deployment procedure on Podman.

== Bare in mind

This guide uses the https://hub.docker.com/r/fametec/glpi[fametec/glpi] docker containers.

== Preparation 

=== Environment variables.

.Production
[source,bash]
----
include::config/env-pro.properties[]
----

.Development
[source,bash]
----
include::config/env-dev.properties[]
----

[CAUTION]
====
The currently implemented GLPI version is `9.5.6`.
====

== PV

Create the folders that will hold GLPI configuration and addons.

[source,bash]
----
sudo mkdir -p ${GLPI_HOME}
----

[source,bash]
----
sudo mkdir -p ${GLPI_HOME}/glpi_web_files
sudo mkdir -p ${GLPI_HOME}/glpi_web_plugins
sudo mkdir -p ${GLPI_HOME}/glpi_web_config
sudo mkdir -p ${GLPI_HOME}/glpi_db_data
----

Assign the correct `user:group` (TBD).

[source,bash]
----
sudo chown $(whoami):$(whoami) -R ${GLPI_HOME}
----

Create the podman volumes that will store the database and odoo web application data.

[source,bash]
----
#podman volume create glpi_db_data --label "name=glpi_db_data" --label "component=pv" --label "part-of=glpi"
#podman volume create glpi_web_data --label "name=glpi_web_files" --label "component=pv" --label "part-of=glpi"
#podman volume create glpi_web_configs --label "name=glpi_web_plugins" --label "component=pv" --label "part-of=glpi"
podman volume create glpi_cron --label "name=glpi_web_cron" --label "component=pv" --label "part-of=glpi"
----

On the `files` PV folder, create the required GLPI sub-folders...

[source,bash]
----
for GLPI_FILES_FOLDER in {_cache,_cron,_dumps,_graphs,_lock,_log,_pictures,_plugins,_rss,_sessions,_tmp,_uploads} 
do
  mkdir ${GLPI_HOME}/glpi_web_files/${GLPI_FILES_FOLDER}
done
----

...and assign the correct `user:group`.

[source,bash]
----
$ sudo chown 48:48 -R  ${GLPI_HOME}/glpi_web_files/*
----

== Installation

Create glpi POD.

[source,bash]
----
$ podman pod create --name ${GLPI_POD_NAME} \
  -p ${APP_HOST_HTTP_PORT}:80 -p ${GRAFANA_HOST_HTTP_PORT}:3000 \
  --label "name=${GLPI_POD_NAME}" --label "environment=${APP_ENV}"
----

=== Deploy the mariadb database

Deploy the `mariadb` database.

[source,bash]
----
podman run --name glpi_mariadb -d --pod ${GLPI_POD_NAME} \
  -e MYSQL_DATABASE=glpi -e MYSQL_USER=glpi -e MYSQL_PASSWORD=admin123 \
  -e MYSQL_ROOT_PASSWORD=admin123 \
  -v glpi_db_data:/var/lib/mysql \
  --label "name=mariadb" --label "component=dabatase" --label "part-of=${GLPI_POD_NAME}" --label "environment=${APP_ENV}" \
  mariadb:latest
----

=== Deploy phpMyAdmin

TBD

=== Deploy GLPI

Deploy the `glpi` application...

 --privileged 

[source,bash]
----
podman run --name ${GLPI_CONTAINER_NAME} --pod ${GLPI_POD_NAME} -d \
  -v "glpi_web_data:/var/www/html/files:z" -v "glpi_web_configs:/var/www/html/plugins:Z" \
  -e GLPI_LANG=en_GB -e MARIADB_HOST=glpi_mariadb -e MARIADB_PORT=3306 \
  -e MARIADB_DATABASE=glpi -e MARIADB_USER=glpi -e MARIADB_PASSWORD=admin123 \
  -e VERSION=9.5.6 -e PLUGINS=all \
  --label "name=glpi" --label "component=web" --label "part-of=${GLPI_POD_NAME}" --label "environment=${APP_ENV}" \
  fametec/glpi:9.5.6
----

Connect to the POD and install GLPI.

[source,bash]
----
$ podman exec -it ${GLPI_CONTAINER_NAME} php bin/console glpi:database:install

+---------------+--------------------------------+
| Database host | mariadb.glpi.svc.cluster.local |
| Database name | glpi                           |
| Database user | glpi                           |
+---------------+--------------------------------+
Do you want to continue ? [Yes/no]
----

Deploy the `glpi` cron...


[source,bash]
----
$ podman run -d --name glpi_cron \
  -v "glpi_cron:/usr/share/nginx/html/glpi:Z" \
  -e MARIADB_DATABASE=glpi -e USER=glpi -e PASSWORD=admin123  -e HOST=glpi_mariadb -e USER=glpi \
  --label "name=glpi_cron" --label "component=cron" --label "part-of=glpi" fametec/glpi:crond
----

== Install Grafana

More information on the link:../../grafana/podman/install.adoc[Grafana Podman Installtion Guide].

Create the *podman volumes* that will store the grafana application data.

[source,bash]
----
podman volume create glpi_grafana --label "name=grafana" --label "component=pv" --label "part-of=glpi" --label "environment=production"
podman volume create glpi_grafana_config --label "name=grafana-config" --label "component=pv" --label "part-of=glpi" --label "environment=production"
----


  -p ${GRAFANA_HOST_HTTP_PORT}:3000 \
  -v glpi_grafana_config:/etc/grafana/grafana.ini:Z
[source,bash]
----
$ podman run -d --name glpi_grafana --pod glpi \
  -v glpi_grafana:/var/lib/grafana:Z \
  --label "name=grafana" --label "component=pv" --label "part-of=glpi" --label "environment=production" \
  grafana/grafana:latest
----

=== Configure Grafana

http://grafana-glpi.localdomain/

Login with `admin`/`admin`

Create datasource to the glpi mariadb database.

New MySQL datasource(`service.namespace.svc.cluster.local`).

.MySQL datasource
[cols="1h,3"]
|===

|Host
| `mariadb.glpi.svc.cluster.local:3306` 

|Database
|`glpi`

|User
|_Check the mariadb configmap_

|Password
|_Check the mariadb secret_

|=== 


== Install as service

Create a user service for managing the `glpi` pod.

On the `$HOME/.config/systemd/user` folder and createthe systemd files.

[source,bash]
----
$ cd $HOME/.config/systemd/user
$ podman generate systemd --new --files --name ${GLPI_POD_NAME}

~/.config/systemd/user/pod-glpi.service
~/.config/systemd/user/container-glpi_web.service
~/.config/systemd/user/container-glpi_grafana.service
~/.config/systemd/user/container-glpi_mariadb.service

----

[source,bash]
----
$ systemctl --user daemon-reload
----


Check service status.

[source,bash]
----
$ systemctl --user status pod-${GLPI_POD_NAME}.service
○ pod-glpi.service - Podman pod-glpi.service
     Loaded: loaded (/home/glpi/.config/systemd/user/pod-glpi.service; disabled; vendor preset: disabled)
     Active: inactive (dead)
       Docs: man:podman-generate-systemd(1)

----

Enable service.

[source,bash]
----
$ systemctl --user enable pod-${GLPI_POD_NAME}.service
----


Start the pod service and make sure the service is running

[source,bash]
----
$ systemctl --user start pod-${GLPI_POD_NAME}.service
----

[source,bash]
----
$ systemctl --user is-active pod-${GLPI_POD_NAME}.service

inactive
----

Check status

[source,bash]
----
systemctl --user is-active pod-glpi.service
systemctl --user is-active container-gitlab_scm.service
systemctl --user is-active container-glpi-runner.service
----

Stop POD.

[source,bash]
----
$ systemctl --user stop pod-glpi.service
----


== Uninstallation

This is the procedure to delete GLPI.

Delete the mariadb database.

[source,bash]
----
helm uninstall --namespace glpi mariadb mariadb
----

Finally delete the PVs...

[source,bash]
----
$ kubectl -n glpi delete -f glpi/helm/glpi-pv-hostPath.yaml
warning: deleting cluster-scoped resources, not scoped to the provided namespace
persistentvolume "glpi-mariadb-data" deleted
persistentvolume "glpi-glpi-files" deleted
persistentvolume "glpi-glpi-plugins" deleted
----

...and it's folders.

[source,bash]
----
$ cd /data/k8s/pv
$ sudo rm -Rf {glpi-mariadb,glpi-glpi-files,glpi-glpi-plugins}
----
