= Odoo Upgrade Guide
Antonio C. <sp38af (at) trikorasolutions (dot) com>
:toc: left
:revdate: {docdate}
:icons: font
:Description: Guide for deploying Odoo as a podman container.

== Upgrade

[.lead]
Upgrade instructions.

=== Requirements

All upgrades require an export file with the database on the starting version.

== 13.0 -> 14.0

[.lead]
Upgrade from `13.0` to `14.0`.

*References*: 

* https://oca.github.io/OpenUpgrade/coverage_analysis/modules130-140.html
* https://github.com/OCA/OpenUpgrade/blob/14.0/openupgrade_scripts/README.rst


=== Start the target container

Stop de odoo 13 container and delete it.

[source,bash]
----
podman stop odoo_web
podman rm odoo_web
----

Start the odoo 14 container.

[source,bash]
----
podman run -it --name odoo_web --privileged --pod odoo -v "odoo_web_data:/var/lib/odoo:z" -v "odoo_web_configs:/etc/odoo:Z"  -v "odoo_web_addons:/mnt/extra-addons:Z" -e POSTGRES_DB=postgres -e USER=odoo -e PASSWORD=1234  -e HOST=odoo_pgsql -e USER=odoo  --label "name=odoo,component=web,part-of=odoo" odoo:14.0 /bin/bash
----

=== Configure starting environment

Install odoo on the starting version, restore the database and start the pod.

Clone the _OpenUpgrade_ GitHub project.

[source,bash]
----
git clone --branch=14.0 --depth=1 --single-branch git@github.com:OCA/OpenUpgrade.git OpenUpgrade-14.0
git clone --depth=1 --single-branch https://github.com/OCA/openupgradelib.git
----

Copy the 2 addon folders to the container under the `/mnt/extra-addons/` folder.

[source,bash]
----
podman cp OpenUpgrade/openupgrade_scripts/ odoo_web:/mnt/extra-addons/
podman cp OpenUpgrade/openupgrade_framework/ odoo_web:/mnt/extra-addons/
----
 
Check the <<openupgradelib,openupgradelib>> section to make sure this Python library is installed. The Python version for Odoo 14.0 is Python 3.7.


==== Add the `openupgrade_scripts` to the odoo installation

Adding the upgrade addon to the installation is done with the `odoo.conf` file.

Download the file.

[source,bash]
----
podman cp odoo_web:/etc/odoo/odoo.conf ./odoo.upg.conf
----

Edit the file `` and add database configuration properties.

[source,]
----
db_host = odoo_pgsql
db_port = 5432
db_user = odoo
db_password = 1234
----

[NOTE]
====
Tthe `upgrade_path` configuration, which probably doesn't exist, pointing to the copied `openupgrade_scripts` subfolder.

[source,]
----
upgrade_path = /mnt/extra-addons/openupgrade_scripts/
server_wide_modules = web,openupgrade_framework
----
====

Save the file and push it into the odoo container.

[source,bash]
----
podman cp odoo.upg.conf odoo_web:/etc/odoo/
----

=== Execute the upgrade

Execute the upgrade by checking the <<execute_the_upgrade,Execute the upgrade>> section.

=== Start the new Odoo version

Before starting the odoo container remove the one used by the upgrade.



[source,bash]
----
podman run --name odoo_web --privileged --pod odoo -d -v "odoo_web_data:/var/lib/odoo:z" -v "odoo_web_configs:/etc/odoo:Z"  -v "odoo_web_addons:/mnt/extra-addons:Z" -e POSTGRES_DB=postgres -e USER=odoo -e PASSWORD=1234  -e HOST=odoo_pgsql -e USER=odoo  --label "name=odoo,component=web,part-of=odoo" odoo:14.0
----



== 14.0 -> 15.0

[source,bash]
----
git clone --branch=15.0 --depth=1 --single-branch git@github.com:OCA/OpenUpgrade.git OpenUpgrade-15.0
----

Copy the 2 addon folders to the container under the `/mnt/extra-addons/` folder.


Start Odoo 15.0.

[source,bash]
----
podman run -it --name odoo_web --privileged --pod odoo -v "odoo_web_data:/var/lib/odoo:z" -v "odoo_web_configs:/etc/odoo:Z"  -v "odoo_web_addons:/mnt/extra-addons:Z" -e POSTGRES_DB=postgres -e USER=odoo -e PASSWORD=1234  -e HOST=odoo_pgsql -e USER=odoo  --label "name=odoo,component=web,part-of=odoo" odoo:15.0 /bin/bash
----

Remove existing openupgrade folders.

[source,bash]
----
podman exec odoo_web rm -Rf /mnt/extra-addons/openupgrade_scripts/
podman exec odoo_web rm -Rf /mnt/extra-addons/openupgrade_framework/
----

Copy OpenUpgrade 15.0 files.

[source,bash]
----
podman cp OpenUpgrade-15.0/openupgrade_scripts/ odoo_web:/mnt/extra-addons/
podman cp OpenUpgrade-15.0/openupgrade_framework/ odoo_web:/mnt/extra-addons/
----

Check the <<openupgradelib,openupgradelib>> section to make sure this Python library is installed. The Python version for Odoo 15.0 is Python 3.9.

Execute the upgrade by checking the <<execute_the_upgrade,Execute the upgrade>> section.

=== Start the new Odoo version

Before starting the odoo container remove the one used by the upgrade.

[source,bash]
----
podman stop odoo_web
podman rm odoo_web
----

Start the container using the correct odoo version.

[source,bash]
----
podman run --name odoo_web --privileged --pod odoo -d -v "odoo_web_data:/var/lib/odoo:z" -v "odoo_web_configs:/etc/odoo:Z"  -v "odoo_web_addons:/mnt/extra-addons:Z" -e POSTGRES_DB=postgres -e USER=odoo -e PASSWORD=1234  -e HOST=odoo_pgsql -e USER=odoo  --label "name=odoo,component=web,part-of=odoo" odoo:15.0
----


== 15.0 -> 16.0

Remove the existing container for Odoo.

[source,bash]
----
podman stop odoo_web
podman rm odoo_web
----

Start Odoo 16.0.

[source,bash]
----
podman run -it --name odoo_web --privileged --pod odoo -v "odoo_web_data:/var/lib/odoo:z" -v "odoo_web_configs:/etc/odoo:Z"  -v "odoo_web_addons:/mnt/extra-addons:Z" -e POSTGRES_DB=postgres -e USER=odoo -e PASSWORD=1234  -e HOST=odoo_pgsql -e USER=odoo  --label "name=odoo,component=web,part-of=odoo" odoo:16.0 /bin/bash
----

In the meantime clone the OpenUpgrade version for Odoo 16.0.

[source,bash]
----
git clone --branch=16.0 --depth=1 --single-branch git@github.com:OCA/OpenUpgrade.git OpenUpgrade-16.0
----

Copy the 2 addon folders to the container under the `/mnt/extra-addons/` folder.


Remove existing openupgrade folders, if they exist.

[source,bash]
----
podman exec odoo_web rm -Rf /mnt/extra-addons/openupgrade_scripts/
podman exec odoo_web rm -Rf /mnt/extra-addons/openupgrade_framework/
----

Copy OpenUpgrade 16.0 files.

[source,bash]
----
podman cp OpenUpgrade-16.0/openupgrade_scripts/ odoo_web:/mnt/extra-addons/
podman cp OpenUpgrade-16.0/openupgrade_framework/ odoo_web:/mnt/extra-addons/
----

Check the <<openupgradelib,openupgradelib>> section to make sure this Python library is installed.  The Python version for Odoo 16.0 is Python 3.9.

Execute the upgrade by checking the <<execute_the_upgrade,Execute the upgrade>> section.

=== Start the new Odoo version

Before starting the odoo container remove the one used by the upgrade.

[source,bash]
----
podman stop odoo_web
podman rm odoo_web
----

Start the container using the correct odoo version.

[source,bash]
----
podman run --name odoo_web --privileged --pod odoo -d -v "odoo_web_data:/var/lib/odoo:z" -v "odoo_web_configs:/etc/odoo:Z"  -v "odoo_web_addons:/mnt/extra-addons:Z" -e POSTGRES_DB=postgres -e USER=odoo -e PASSWORD=1234  -e HOST=odoo_pgsql -e USER=odoo  --label "name=odoo,component=web,part-of=odoo" odoo:16.0
----


== Common instructions

=== Execute the upgrade [[execute_the_upgrade]]

Execute the upgrade.

[source,bash]
----
odoo -c /etc/odoo/odoo.upg.conf --database=trikorasolns --upgrade-path=/mnt/extra-addons/openupgrade_scripts/scripts --load=base,web,openupgrade_framework --update all --stop-after-init --i18n-overwrite
----

=== openupgradelib [[openupgradelib]]

Install the latest `openupgradelib` version, locally.

NOTE: 

* For Odoo 13.0 use Python 3.7.
* For Odoo 14.0 use Python 3.9.

Set the Python version.

[source,bash]
----
ODOO_PYTHON_VERSION=3.7
----

==== On local machine

[NOTE]
====
If required, install Python 3.7.

[source,bash]
----
sudo dnf install python${ODOO_PYTHON_VERSION}
----

And also install pip for version 3.7.

[source,bash]
----
python${ODOO_PYTHON_VERSION} -m ensurepip --upgrade
----
====

Install `openupgradelib` from the GitHub main branch.

[source,bash]
----
python${ODOO_PYTHON_VERSION} -m pip install git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib
pip3.7 install git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib
----

[CAUTION]
====
*Before making the copy*, check that the 
`/var/lib/odoo/.local/lib/python${ODOO_PYTHON_VERSION}` folder exists on the 
 Odoo container.

If the folder doesn't exist create it by installing anything, _e.g._ `yq`.

[source,bash]
----
python3.9 -m pip install yq
----

====

Copy the files to the Odoo container.

[source,bash]
----
podman cp ${HOME}/.local/lib/python${ODOO_PYTHON_VERSION}/site-packages/openupgradelib/ odoo_web:/var/lib/odoo/.local/lib/python${ODOO_PYTHON_VERSION}/site-packages/
podman cp ${HOME}/.local/lib/python${ODOO_PYTHON_VERSION}/site-packages/openupgradelib-3.6.2.dev10+g9d08460-py${ODOO_PYTHON_VERSION}.egg-info/ odoo_web:/var/lib/odoo/.local/lib/python${ODOO_PYTHON_VERSION}/site-packages/
----

[NOTE]
====
This doesn't work with Python 3.7 and IDK why!

Generate pip `requirements.txt` file for the `openupgradelib` version.

[source,bash]
----
python3.7 -m pip freeze | grep openupgradelib > requirements.txt
----

Generate a requireements folder with the downloaded `openupgradelib` library.

[source,bash]
----
mkdir pip-reqs
python3.7 -m pip download -r requirements.txt -d pip-reqs/
----

Copy the requirements to Odoo container.

[source,bash]
----
podman cp pip-reqs/ odoo_web:/opt/
----

On the Odoo container, install `openupgradelib` from the requirements folder.

[source,bash]
----
pip3 uninstall -y openupgradelib
pip3 install openupgradelib --find-links=/opt/pip-reqs/
----
====

[NOTE]
====
Old instructions for historical purposes only.

On the podman bash shell, install openupgradelib

[source,bash]
----
pip3 install openupgradelib
pip3 install git+https://github.com/OCA/openupgradelib.git@master#egg=openupgradelib
pip3 install "openupgradelib==2.0.0"
----

To uninstall.

[source,bash]
----
pip3 uninstall -y openupgradelib
----

====


== Troubleshooting

=== 13.0 -> 14.0

==== column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist

[source,]
----
2024-04-30 07:55:02,772 50 INFO trikorasolns odoo.models: Storing computed values of res.company.account_tax_fiscal_country_id 
2024-04-30 07:55:02,965 50 ERROR trikorasolns odoo.sql_db: bad query: ALTER TABLE "account_reconcile_model_analytic_tag_rel" ADD FOREIGN KEY ("account_reconcile_model_line_id") REFERENCES "account_reconcile_model_line"("id") ON DELETE cascade
ERROR: column "account_reconcile_model_line_id" referenced in foreign key constraint does not exist
----

==== KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7f76702c3378>, 'base.module_category_services_timesheets')


=== 15.0

=== Uncaught Promise > While parsing modifiers for span: for modifier "invisible": Unknown field meeting_count in domain

==== Problem

When opening a CRM lead the application fails with an error

[source,]
----
Uncaught Promise > While parsing modifiers for span: for modifier "invisible": Unknown field meeting_count in domain
----

==== Cause

==== Solution

1. Go to Configuration and enable the developer mode
2. Go to Configuration > Translations > Translated terms
Search for "meeting_count" as translation value
3. Replace every occurrence of "meeting_count" by "calendar_event_count"
4. Go back to the configuration > Manage Languages
5. Update every languages 


=== 15.0 -> 16.0

==== ERROR trikorasolns odoo.sql_db: bad query: UPDATE "ir_rule" SET "name" = 'user: read own attendance only'


==== Problem

[source,]
----
2024-04-30 16:05:38,744 24 ERROR trikorasolns odoo.sql_db: bad query: UPDATE "ir_rule" SET "name" = 'user: read own attendance only', "perm_create" = false, "perm_write" = false, "write_date" = '2024-04-30 16:05:38.358473', "write_uid" = 1 WHERE id IN (131)
ERROR: new row for relation "ir_rule" violates check constraint "ir_rule_no_access_rights"
DETAIL:  Failing row contains (131, user: read own attendance only, t, 360, [('employee_id.user_id','=',user.id)], f, f, f, f, f, 1, 2019-12-04 00:53:27.393718, 1, 2024-04-30 16:05:38.358473).
 
2024-04-30 16:05:38,744 24 ERROR trikorasolns OpenUpgrade: hr_attendance: error in migration script /mnt/extra-addons/openupgrade_scripts/scripts/hr_attendance/16.0.2.0/post-migration.py: while parsing /mnt/extra-addons/openupgrade_scripts/scripts/hr_attendance/16.0.2.0/noupdate_changes.xml:9, somewhere inside
<record id="hr_attendance_rule_attendance_employee" model="ir.rule">
    <field name="name">user: read own attendance only</field>
    <field name="perm_create" eval="0"/>
    <field name="perm_write" eval="0"/>
  </record> 
2024-04-30 16:05:38,744 24 ERROR trikorasolns OpenUpgrade: while parsing /mnt/extra-addons/openupgrade_scripts/scripts/hr_attendance/16.0.2.0/noupdate_changes.xml:9, somewhere inside
<record id="hr_attendance_rule_attendance_employee" model="ir.rule">
    <field name="name">user: read own attendance only</field>
    <field name="perm_create" eval="0"/>
    <field name="perm_write" eval="0"/>
  </record> 
----

