---
- name: "Install Apache Superset - {{ app_version }}"
  hosts: "{{ k8s_host | default('localhost') }}"
  gather_facts: "{{ gathering_host_info | default('true') | bool == true }}"

  pre_tasks:
    - name: "Validate variables"
      ansible.builtin.assert:
        that:
          # - "pv_root_folder is defined"
          - "app_name is defined"
          - "app_namespace is defined"
        fail_msg: "Missing required parameters"

  tasks:

    - name: "Template Superset secret file"
      ansible.builtin.template:
        src: "superset-secret.yaml.j2"
        dest: "/tmp/superset-secret.yaml"
        mode: '0600'

    - name: "Deploy Odoo with Helm"
      kubernetes.core.helm:
        name: "apache-superset"
        chart_ref: "superset/superset"
        release_namespace: "{{ app_namespace }}"
        wait: true
        replace: true
        values_files:
          - superset-values.yaml
      register: superset_helm_install_res

    - name: "Remove secret file template"
      ansible.builtin.file:
        path: /tmp/superset-secret.yaml
        state: absent
...
