app_name: apache-superset
app_namespace: apache-superset
app_version: "5.0.0"

db_name: apachesuperset
db_user: apachesuperset
db_image_tag: "17.9"
mariadb_version: "10.11.14"

namespace_quotas:
  limits:
    cpu: 2500m
    memory: 15Gi
  requests:
    cpu: 1400m
    memory: 5000Mi

app_resources:
  limits:
    cpu: "1500m"
    memory: "3Gi"
  requests:
    cpu: "500m"
    memory: "1000Mi"
