= GLPI Deploy Guide (Helm)
:author:    Antonio C.
:email:     <ac (at) trikorasolutions (dot) com>
:Date:      2022/05/02
:revdate: {docdate}
:toc:       left
:toc-title: Table of Contents
:icons: font
:description: This section describes the GLPI deployment procedure.

== Bare in mind

This guide uses the https://github.com/trikorasolns/helm-charts[trikorasolns/helm-charts] repository helm charts.

All commands assume the shell is connected to the correct k8s instance.

[source,bash]
----
$ export KUBECONFIG=~/.kube/my-config-file
----

== System requirements 

Install python requirements.

[source,bash]
----
pip install -r glpi/k8s/ansible/requirements.txt
----

=== Required information

Required variables.

.Helm install prepare parameters
[cols="20%,80%"]
|===
|Field name |Description


| `app_namespace`

[.fuchsia]#string#

[.red]#required# 

a| Namespace used in kubernetes for deploying the application.

It's also the root folder for the application PV folders.

| `db_name`

[.fuchsia]#string#

[.red]#required# 

a| Database name

| `db_user`

[.fuchsia]#string#

[.red]#required# 

a| Database user

| `db_password`

[.fuchsia]#string#

[.red]#required# 

a| Database password

| `db_root_password`

[.fuchsia]#string#

[.red]#required# 

a| Database root password

| `glpi_version`

[.fuchsia]#string#

[.red]#required# 

a| GLPI version being installed. 

[NOTE]
====
ATTOW ths version is only used to inform k8s object metadata.
====

| `k8s_host`

[.fuchsia]#string#

[.red]#required# 

a| Kubernetes node

| `trikora_helm_project_dir`

[.fuchsia]#string#

a| Folder, on the host system, with a clone of the link:https://github.com/trikorasolns/helm-charts[TrikoraSolutions Helm Charts] Github repository.

| `k8s.pv_root_folder`

[.fuchsia]#string#

a| Root folder on the node FS where the required PV sub-folders will be created.

[NOTE]
====
The default installation uses `hostPath` for persistence.
====

[NOTE]
====
Can be provided by the host information on the Ansible Inventory.
====

|===

Create a yaml file with the values for each of the required variables.

.Sample data values file
[source,yaml]
----
app_namespace: glpi
db_name: glpi
db_user: glpi
db_password: glpi
db_root_password: glpi
glpi_url: glpi.localdomain
glpi_version: "10.0.9"
k8s_host: myhost
trikora_helm_project_dir: /tmp/trikora-helm-charts
----

== Prepare

Create the namespace.

=== Host Path

[source,bash]
----
ansible-playbook kubernetes/ansible/host_path/app-prepare-playbook.yaml \
  -e "@glpi/k8s/ansible/defaults/main.yaml"
----

Create HostPath PVs and their supporting folders.

The persistence information is provided in the 
 link:ansible/default/main.yaml[] file.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-prepare-playbook.yaml -K \
  -e "@glpi/k8s/ansible/defaults/main.yaml"
----

== Install


=== MariaDB

This will deploy a MariaDB database on the application namespace.

  -e "@glpi/k8s/ansible/defaults/main.yaml" \

[source,bash]
----
ansible-playbook mariadb/k8s/helm/ansible/mariadb-install-playbook.yaml \
  -e "@glpi/k8s/ansible/defaults/main.yaml" \
  -e "@kubernetes/storage/ceph/ansible/defaults/main.yaml" \
  -e "@_local_config/glpi.yaml" \
  -e db_password=${DB_PASSWORD} \
  -e db_root_password=${DB_PASSWORD}
----

If you want to Restore a previous GLPI backup check the 
 link:./backupNrestore.adoc[Backup & Restore] guide at this point as some 
 tasks need to be executed before starting the application.

=== GLPI

Deploy the `glpi` application using the `trikorasolns/glpi` helm chart.

[source,bash]
----
ansible-playbook glpi/k8s/helm/ansible/glpi-install-playbook.yaml \
  -e @kubernetes/storage/ceph/ansible/defaults/main.yaml \
  -e "@glpi/k8s/ansible/defaults/main.yaml" \
  -e "@_local_config/network.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD}
----

If deploying the application to restore an existing backup consider adding 
 the `GLPICRYPT` environment variable so the `glpycrypt.key` file is restored 
 instead of GLPI having a new one generated.

[NOTE]
====
To generate the base64 encoding perform the following steps.

Tar the glpicrypt file. The name of the file inside the TAR GZ must be 
 `glpicrypt.key`.

[source,bash]
----
tar czvf glpicrypt.key.tgz glpicrypt.key
----

Base64 encode the file.

[source,bash]
----
cat /tmp/glpicrypt.key.tgz | base64 -w 0
----

These are the contents to be passed to the `glpicrypt_targz_file`.
====

[source,bash]
----
ansible-playbook glpi/k8s/helm/ansible/glpi-install-playbook.yaml \
  -e "@_local_config/glpi.yaml" \
  -e "@_local_config/network.yaml" \
  -e "@glpi/k8s/ansible/defaults/main.yaml" \
  -e db_password=${DB_PASSWORD} \
  -e glpicrypt_targz_file="${GLPICRYPT_TARGZ_FILE}"
----

=== Grafana

[source,bash]
----
ansible-playbook glpi/k8s/helm/ansible/grafana-install-playbook.yaml \
  -e "@glpi/k8s/ansible/defaults/main.yaml" \
  -e "@_local_config/network.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM}
----

== Uninstall

Use the following playbook command to uninstall the helm chart. 

This playbook will perform the following tasks:

* Execute the Helm uninstall that will remove the GLPI deployment and related
 resources
* Clean the GLPI PV refs so their state becomes _Available_. Otherwise the 
 state would be _Released_.
* Reset the PV _Claim Ref_ to the original PVC so when re-installing the PVC 
 won't be attached to the wrong PV.

[source,bash]
----
ansible-playbook glpi/k8s/helm/ansible/glpi-uninstall-playbook.yaml \
  -e "@glpi/k8s/ansible/defaults/main.yaml"
----

[WARNING]
====
Decide what to do with the _hostPath_ folders on the kubernetes server.

ATTOW their contents can be recreate using the following bash command when 
 located under the root folder for the GLPI files.

[source,bash]
----
sudo rm -Rf glpi-files/ glpi-log/ glpi-marketplace/ glpi-plugins/ ; mkdir -p glpi-config glpi-files/{'_cron','_dumps','_graphs','_lock','_pictures','_plugins','_rss','_sessions','_tmp','_uploads','_cache/templates'} glpi-log glpi-marketplace glpi-plugins ; chmod 777 -R glpi-files/ glpi-log/ glpi-marketplace/ glpi-plugins/ ; sudo chown 33:33 -R glpi-files/ glpi-log/ glpi-marketplace/ glpi-plugins/
----
====

Delete the GLPI namespace.

[source,bash]
----
kubectl delete ns glpi
----

Cleanup the PVs.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-cleanup-playbook.yaml -K \
  -e "@glpi/k8s/ansible/defaults/main.yaml"
----

Don't forget to check and eventually patch the _Released_ PVs.

[source,bash]
----
kubectl get pv
----

[source,bash]
----
NAME                             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS
glpi-glpi-etc-local-pv       5Gi        RWO            Retain           Released
glpi-glpi-var-log-local-pv   5Gi        RWO            Retain           Released
glpi-glpi-var-opt-local-pv   20Gi       RWO            Retain           Released
----

Or completely remove everything.

[NOTE]
====
The persistence information is provided in the 
 link:ansible/default/main.yaml[] file.
====

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-cleanup-playbook.yaml -K \
  -e "@glpi/k8s/ansible/defaults/main.yaml"
----

=== MariaDB

This will uninstall the MariaDB database chart on the application namespace.

[source,bash]
----
ansible-playbook mariadb/k8s/helm/ansible/mariadb-uninstall-playbook.yaml \
  -e "@_local_config/glpi.yaml" \
  -e db_password=${DB_PASSWORD}
----




== Manual Install

=== Prepare the k8s host

The environment is prepared with the following tasks.

* Install the requirements on the server
* Create the required `hostPath` folder structure
* Create the namespace

.Prepare the k8s host FS
[source,bash]
----
ansible-playbook glpi/k8s/ansible/install-helm-prepare-fs.yaml \
  -e k8s_host=${K8S_HOST} \
  -e app_namespace=${GLPI_NAMESPACE} \
  -K
----

[WARNING]
====
Make sure the default kubeconfig is pointing to the correct kubernetes cluster before running the next playbook.
====

.Prepare the k8s host
[source,bash]
----
ansible-playbook glpi/k8s/ansible/install-helm-prepare.yaml \
  -e k8s_host=${K8S_HOST} \
  -e app_namespace=${GLPI_NAMESPACE}
----

=== Install the MariaDB database

Install the MariaDB database

.Playbook command to install the MariaDB database.
[source,bash]
----
ansible-playbook glpi/k8s/ansible/install-helm-database.yaml \
  -e app_namespace=${GLPI_NAMESPACE} \
  -e db_name=glpi \
  -e db_user=glpi \
  -e db_password=glpi \
  -e db_root_password=glpi \
  -e glpi_version="10.0.9" \
  -e trikora_helm_project_dir=${TRIKORA_HELM_PROJECT_DIR} \
  -e k8s_host=${K8S_HOST}
----

=== Install GLPI

Install.

[source,bash]
----
ansible-playbook glpi/k8s/ansible/install-helm-glpi.yaml \
  -e app_namespace=${GLPI_NAMESPACE} \
  -e db_name=glpi \
  -e db_user=glpi \
  -e db_password=glpi \
  -e db_root_password=glpi \
  -e glpi_version="10.0.9" \
  -e glpi_url=${GLPI_URL} \
  -e trikora_helm_project_dir=${TRIKORA_HELM_PROJECT_DIR} \
  -e k8s_host=${K8S_HOST}
----

Uninstall

[source,bash]
----
ansible-playbook glpi/k8s/ansible/uninstall-helm-glpi.yaml \
  -e app_namespace=${GLPI_NAMESPACE} \
  -e db_name=glpi \
  -e db_user=glpi \
  -e db_password=glpi \
  -e db_root_password=glpi \
  -e glpi_version="10.0.9" \
  -e glpi_url=${GLPI_URL} \
  -e trikora_helm_project_dir=${TRIKORA_HELM_PROJECT_DIR} \
  -e k8s_host=${K8S_HOST}
----

=== Install Grafana

Install Grafana.

[source,bash]
----
ansible-playbook glpi/k8s/ansible/install-helm-grafana.yaml \
  -e @/tmp/data_values_file.yaml \
  -e trikora_helm_project_dir=${TRIKORA_HELM_PROJECT_DIR} \
  -e k8s_host=${K8S_HOST}
----

Uninstall Grafana.

[source,bash]
----
ansible-playbook glpi/k8s/ansible/uninstall-helm-grafana.yaml \
  -e @/tmp/data_values_file.yaml \
  -e trikora_helm_project_dir=${TRIKORA_HELM_PROJECT_DIR} \
  -e k8s_host=${K8S_HOST}
----


=== Install phpMyAdmin

Install phpMyAdmin.

.Playbook command to install the phpMyAdmin console.
[source,bash]
----
ansible-playbook glpi/k8s/ansible/install-helm-phpmyadmin.yaml \
  -e app_namespace=${GLPI_NAMESPACE} \
  -e db_name=glpi \
  -e db_user=glpi \
  -e db_password=glpi \
  -e db_root_password=glpi \
  -e glpi_version="10.0.9" \
  -e trikora_helm_project_dir=${TRIKORA_HELM_PROJECT_DIR} \
  -e k8s_host=${K8S_HOST}
----


== Installation (Deprecated)

=== Create PV and folders

The root folder for the PV is defined with the `PV_ROOT_FOLDER` environment variable.

First connect to the k8s host and create the folders that will hold the PVs.

[source,bash]
----
$ mkdir -p ${PV_ROOT_FOLDER}/glpi 
$ pushd ${PV_ROOT_FOLDER}/glpi 
$ mkdir {glpi-mariadb,glpi-glpi-files,glpi-glpi-plugins}
$ popd
----

Set folder permissions.

[source,bash]
----
$ chmod 777 -R ${PV_ROOT_FOLDER}/glpi/glpi-mariadb
----

Create the PVs.

[NOTE]
====
Prior to applying the PV script check the contents of the `yaml ` file to make sure
the routes are correct.
====

[source,bash]
----
$ jinja2 --format=yaml -DPV_ROOT_FOLDER=${PV_ROOT_FOLDER} glpi/k8s/helm/pv-glpi-hostPath.yaml | kubectl apply -f -
$ jinja2 --format=yaml -DPV_ROOT_FOLDER=${PV_ROOT_FOLDER} glpi/k8s/helm/pv-mariadb-hostPath.yaml | kubectl apply -f -

persistentvolume/glpi-mariadb-data created
persistentvolume/glpi-glpi-files created
persistentvolume/glpi-glpi-plugins created
----

=== Create GLPI file 

On the `files` PV folder, create the required GLPI sub-folders...

[source,bash]
----
$ pushd ${PV_ROOT_FOLDER}/glpi/glpi-glpi-files
$ mkdir {_cache,_cron,_dumps,_graphs,_lock,_log,_pictures,_plugins,_rss,_sessions,_tmp,_uploads}
----

...and assign the correct `user:group`.

[source,bash]
----
$ sudo chown 48:48 -R *
----

=== Create the namespace

Create glpi namespace.

[source,bash]
----
$ kubectl create namespace glpi
$ kubectl label namespaces glpi app.kubernetes.io/name=glpi
$ kubectl label namespaces glpi app.kubernetes.io/version=9.5.6
----

=== Deploy the mariadb database

Deploy the `mariadb` database using the `trikorasolns/mariadb` helm chart.

[source,bash]
----
$ jinja2 --format=yaml -DPV_ROOT_FOLDER=${PV_ROOT_FOLDER} glpi/k8s/helm/pv-glpi-hostPath.yaml > /tmp/pv-glpi-hostPath.yaml
$ kubectl apply -f /tmp/pv-glpi-hostPath.yaml
----

[source,bash]
----
$ jinja2 --format=yaml -DDB_PASSWORD=${DB_PASSWORD} -DDB_ROOT_PASSWORD=${DB_ROOT_PASSWORD} glpi/k8s/helm/helm-mariadb-values.yaml > /tmp/helm-mariadb-values.yaml
$ helm install --namespace glpi -f /tmp/helm-mariadb-values.yaml mariadb mariadb
----

Deploy phpMyAdmin

References:

* https://www.phpmyadmin.net/

[source,bash]
----
$ helm install --namespace glpi phpmyadmin phpmyadmin
----

=== Deploy GLPI

Deploy the `glpi` application using the `trikorasolns/glpi` helm chart.

[source,bash]
----
$ jinja2 --format=yaml -DGLPI_URL=${GLPI_URL} glpi/k8s/helm/helm-glpi-values.yaml > /tmp/helm-glpi-values.yaml
$ helm install --namespace glpi -f /tmp/helm-glpi-values.yaml glpi glpi
----

Follow the instructions to obtain the pod name.

[source,bash]
----
$ POD_NAME=$(kubectl get pods --namespace glpi -l "app.kubernetes.io/name=glpi,app.kubernetes.io/instance=glpi" -o jsonpath="{.items[0].metadata.name}")
----

Install GLPI.

[source,bash]
----
$ kubectl -n glpi exec -it ${POD_NAME} -- php bin/console glpi:database:install

PHP Warning:  Table glpi_configs does not exists in /var/www/html/inc/dbmysql.class.php on line 1010
PHP Warning:  Table glpi_configs does not exists in /var/www/html/inc/dbmysql.class.php on line 1010
+---------------+--------------------------------+
| Database host | mariadb.glpi.svc.cluster.local |
| Database name | glpi                           |
| Database user | glpi                           |
+---------------+--------------------------------+
Do you want to continue ? [Yes/no]
----

=== Update GLPI

To make configuration changes update the corresponding files and redeploy with `helm upgrade`.

[source,bash]
----
$ helm upgrade --namespace glpi -f glpi/helm/values.yaml glpi glpi
----


== Uninstallation

This is the procedure to delete GLPI.

Delete the mariadb database.

[source,bash]
----
helm uninstall --namespace glpi mariadb mariadb
----

Finally delete the PVs...

[source,bash]
----
$ kubectl -n glpi delete -f glpi/helm/glpi-pv-hostPath.yaml
warning: deleting cluster-scoped resources, not scoped to the provided namespace
persistentvolume "glpi-mariadb-data" deleted
persistentvolume "glpi-glpi-files" deleted
persistentvolume "glpi-glpi-plugins" deleted
----

...and it's folders.

[source,bash]
----
$ cd /data/k8s/pv
$ sudo rm -Rf {glpi-mariadb,glpi-glpi-files,glpi-glpi-plugins}
----
