= Gitlab Deployment Guide (helm)
:author:    Antonio C.
:email:     <sp38af (at) trikorasolutions (dot) com>
:Date:      20220502
:revdate: {docdate}
:toc:       left
:toc-title: Table of Contents
:icons: font
:description: This document describes the k8s installation process for GitLab using Helm Charts.

== References

  * https://docs.gitlab.com/charts/

== Prepare

Create the namespace.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-prepare-playbook.yaml \
  -e "@gitlab/k8s/ansible/defaults/main.yaml"
----

Create HostPath PVs and their supporting folders.

The persistence information is provided in the 
 link:ansible/default/main.yaml[] file.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-prepare-playbook.yaml -K \
  -e "@gitlab/k8s/ansible/defaults/main.yaml"
----

== Install 

== PostgreSQL

Install PostgreSQL. The PV have already been provisioned in the preparation 
 steps.

This will deploy a PostgreSQL database on the application namespace.

[source,bash]
----
ansible-playbook pgsql/k8s/helm/ansible/pgsql-install-playbook.yaml \
  -e "@gitlab/k8s/ansible/defaults/main.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD}
----

== Redis

[source,bash]
----
ansible-playbook gitlab/k8s/helm/ansible/redis-install-playbook.yaml \
  -e "@gitlab/k8s/ansible/defaults/main.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM}
----

Installing manually with Helm would be.

[source,bash]
----
helm upgrade --install --namespace gitlab redis ./redis
----

To remove redis execute the corresponding uninstall playbook.

[source,bash]
----
ansible-playbook gitlab/k8s/helm/ansible/redis-install-playbook.yaml \
  -e "@gitlab/k8s/ansible/defaults/main.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM}
----

== GitLab

Deploy the `gitlab` application using the `trikorasolns/gitlab` helm chart.

[source,bash]
----
ansible-playbook gitlab/k8s/helm/ansible/gitlab-install-playbook.yaml \
  -e "@gitlab/k8s/ansible/defaults/main.yaml" \
  -e "@_local_config/network.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD} 
----

== Uninstall

Use the following playbook command to uninstall the helm chart.

[source,bash]
----
ansible-playbook gitlab/k8s/helm/ansible/gitlab-uninstall-playbook.yaml \
  -e "@gitlab/k8s/ansible/defaults/main.yaml" \
  -e "@_local_config/network.yaml" \
  -e trikora_helm_project_dir=${TRIKORA_HELM} \
  -e db_password=${DB_PASSWORD} 
----

Delete the GitLab namespace.

[source,bash]
----
kubectl delete ns gitlab
----

Cleanup the PVs.

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-cleanup-playbook.yaml -K \
  -e "@gitlab/k8s/ansible/defaults/main.yaml"
----

Don't forget to check and eventually patch the _Released_ PVs.

[source,bash]
----
kubectl get pv
----

[source,bash]
----
NAME                             CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS
gitlab-gitlab-etc-local-pv       5Gi        RWO            Retain           Released
gitlab-gitlab-var-log-local-pv   5Gi        RWO            Retain           Released
gitlab-gitlab-var-opt-local-pv   20Gi       RWO            Retain           Released
----

Or completely remove everything.

[NOTE]
====
The persistence information is provided in the 
 link:ansible/default/main.yaml[] file.
====

[source,bash]
----
ansible-playbook --limit ${K8S_HOST} kubernetes/ansible/host_path/app-pv-cleanup-playbook.yaml -K \
  -e "@gitlab/k8s/ansible/defaults/main.yaml"
----

== Manual steps

== Manually Install 

[source,bash]
----
kubectl patch pv gitlab-gitlab-etc-local-pv gitlab-gitlab-var-opt-local-pv gitlab-gitlab-var-log-local-pv -p '{"spec":{"claimRef": null}}'
----

[source,bash]
----
$ jinja2 --format=yaml -DGITLAB_URL=${GITLAB_URL} -DGITLAB_IP=${GITLAB_IP} -DGITLAB_VERSION=15.8.2 gitlab/k8s/helm/helm-gitlab-values.yaml > /tmp/helm-gitlab-values.yaml
$ helm upgrade --install --namespace gitlab -f /tmp/helm-gitlab-values.yaml gitlab gitlab
----


[source,bash]
----
$ ansible-playbook gitlab/k8s/ansible/playbook-gitlab-prepare.yaml -e k8s_host=${VM_NAME} -e gitlab_hostname=${GITLAB_HOSTNAME} -e @gitlab/k8s/ansible/defaults/main.yaml -K
$ helm upgrade --install --namespace gitlab gitlab ./gitlab
----

=== Manual Uninstall

GitLab

[source,bash]
----
$ helm uninstall --namespace gitlab gitlab
$ ansible-playbook gitlab/k8s/ansible/playbook-gitlab-remove.yaml -e k8s_host=${VM_NAME} -e @gitlab/k8s/ansible/defaults/main.yaml -K
----

PostgreSQL

[source,bash]
----
$ helm uninstall --namespace gitlab postgresql
$ ansible-playbook gitlab/k8s/ansible/playbook-pgsql-remove.yaml -e k8s_host=${VM_NAME} -e @gitlab/k8s/ansible/defaults/main.yaml -K
----

== Preparation 

=== Ansible

[source,bash]
----
$ ansible-playbook gitlab/k8s/ansible/install-preparation.yaml  -e k8s_host=${VM_NAME} -K
----

[source,bash]
----
$ ansible-playbook gitlab/k8s/ansible/playbook-install-prepare.yaml -e k8s_host=${VM_NAME} -e gitlab_hostname=${GITLAB_HOSTNAME} -e @gitlab/k8s/ansible/defaults/main.yaml -K
----

=== Create PV and folders

First connect to the k8s host and create the folders that will hold the PVs.

[source,bash]
----
$ cd /data/k8s/pv
$ sudo mkdir -p {gitlab/postgresql-data,gitlab/gitaly-data,gitlab/gitlab-var-opt,gitlab/gitlab-var-log,gitlab/gitlab-etc}
----

Assign the correct `user:group`.

[source,bash]
----
$ sudo chown 999 -R gitlab/postgresql-data
$ sudo chown 1000 -R gitlab/gitlab-*
----

... or ??? ...

[source,bash]
----
$ sudo chmod 777 -R gitlab/postgresql-data
$ sudo chmod 777 -R gitlab/gitlab-*
----

Create the PVs.

[source,bash]
----
$ kubectl apply -f gitlab/helm/gitlab-pv-hostPath.yaml
----

== Installation

Create `gitlab` namespace.

[source,bash]
----
$ kubectl create namespace gitlab
----

=== PostgreSQL

[source,bash]
----
$ helm install --namespace gitlab postgresql ./postgresql
----

=== PHP My Admin

TODO: Isn't working.

[source,bash]
----
$ helm install --namespace gitlab -f gitlab/helm/pgadmin-values-dev.yaml pgadmin ./pgadmin
----

=== Redis

[source,bash]
----
$ helm install --namespace gitlab redis ./redis
----


== Uninstallation

=== PostgreSQL

[source,bash]
----
$ helm uninstall --namespace gitlab postgresql ./postgresql
----
