= Gitlab Upgrade Guide
:author:    Antonio C.
:email:     <ac (at) trikorasolutions (dot) com>
:revdate: {docdate}
:toc:       left
:toc-title: Table of Contents
:icons: font
:description: This section describes the Gitlab upgrade steps.

:toc:

References: 

* https://docs.gitlab.com/ee/update/plan_your_upgrade.html
* Upgrade paths: https://docs.gitlab.com/update/upgrade_paths/
* https://docs.gitlab.com/administration/package_information/postgresql_versions/

== Upgrade

[.lead]
Instructions to upgrade Gitlab.

The system must be up and running.

* PostgreSQL database
* Redis
* Gitlab

Update the helm values file with the target version and container image tag 
 for that version.

[source,yaml]
----
app_version: "18.3.1"
app_image_tag: "18.3.1-ee.0"
----

Execute the link:./install-helm.adoc[GitLab installation Ansible Playbook].

Follow the upgrade process by tailing the GitLab pod.

[source,bash]
----
kubectl -n gitlab logs -f $(kubectl get pods -n gitlab -o json | jq -r '.items.[] | select( (.metadata.name | startswith("gitlab")) and .status.phase == "Running")'.metadata.name)
----

After it's finished, check status...

[source,bash]
----
kubectl -n gitlab exec -it $(kubectl get pods -n gitlab -o json | jq -r '.items.[] | select( (.metadata.name | startswith("gitlab")) and .status.phase == "Running")'.metadata.name) -- gitlab-ctl status
----

[source,]
----
run: alertmanager: (pid 723) 2968s; run: log: (pid 513) 2981s
run: gitaly: (pid 529) 2979s; run: log: (pid 309) 3194s
run: gitlab-exporter: (pid 707) 2969s; run: log: (pid 473) 2991s
run: gitlab-kas: (pid 678) 2970s; run: log: (pid 342) 3184s
run: gitlab-workhorse: (pid 689) 2970s; run: log: (pid 423) 3005s
run: logrotate: (pid 271) 3202s; run: log: (pid 279) 3201s
run: nginx: (pid 445) 3000s; run: log: (pid 464) 2997s
run: prometheus: (pid 709) 2969s; run: log: (pid 495) 2985s
run: puma: (pid 365) 3018s; run: log: (pid 372) 3017s
run: sidekiq: (pid 380) 3012s; run: log: (pid 388) 3011s
run: sshd: (pid 27) 3219s; run: log: (pid 268) 3206s
----

...and also check gitlab version.

[source,bash]
----
kubectl -n gitlab exec -it $(kubectl get pods -n gitlab -o json | jq -r '.items.[] | select( (.metadata.name | startswith("gitlab")) and .status.phase == "Running")'.metadata.name) -- gitlab-rake gitlab:env:info
----

[source,]
----
System information
System:		
Proxy:		no
Current User:	git
Using RVM:	no
Ruby Version:	3.0.6p216
Gem Version:	3.4.18
Bundler Version:2.4.18
Rake Version:	13.0.6
Redis Version:	7.0.12
Sidekiq Version:6.5.7
Go Version:	unknown

GitLab information
Version:	16.3.9-ee
Revision:	75488cc22f5
Directory:	/opt/gitlab/embedded/service/gitlab-rails
DB Adapter:	PostgreSQL
DB Version:	13.11
URL:		http://gitlab.trikorasolutions.net
HTTP Clone URL:	http://gitlab.trikorasolutions.net/some-group/some-project.git
SSH Clone URL:	ssh://git@gitlab.trikorasolutions.net:30022/some-group/some-project.git
Elasticsearch:	no
Geo:		no
Using LDAP:	no
Using Omniauth:	yes
Omniauth Providers: 

GitLab Shell
Version:	14.26.0
Repository storages:
- default: 	unix:/var/opt/gitlab/gitaly/gitaly.socket
GitLab Shell path:		/opt/gitlab/embedded/service/gitlab-shell

Gitaly
- default Address: 	unix:/var/opt/gitlab/gitaly/gitaly.socket
- default Version: 	16.3.9
- default Git Version: 	2.41.0.gl1
----

Log into the application and check it works correctly.

Finally, backup you upgraded system using the backup Ansible Playbook.

== Upgrading the database

If an upgrade requires upgrading the database version perform the following 
 steps.

Backup the GitLab installation using the GitLab backup Ansible Playbook.

Uninstall all components:

* GitLab
* Redis
* PostgreSQL

Update the database version variable (`db_image_tag`) on the helm variables 
 file.

[source,yaml]
----
db_image_tag: 16.8
----

Install the new PostgreSQL database.

Install Redis.

Install GitLab with the version backed up.

Restore the backup.

== Execution history

[%header,cols="1m,1m"]
|===

| GitLab Version
| PostgreSQL Version

|  18.3.1 | 16.8
|  18.2.5 | 16.8
|  17.11.7 | 16.8
|  17.8.7 | 16.8
2+| Backup GitLab 17.5.5, upgrade PostgreSQL to 16.8 and restore GitLab
|  17.5.5 | 14.11
|  17.3.7 | 14.11
|  17.1.8 | 14.11
2+| Backup GitLab 16.11.10, upgrade PostgreSQL to 14.11 and restore GitLab
|  16.11.10 | 13.11
|  16.7.10 | 13.11
|  16.3.9 | 13.11
| 15.11.13 | 13.11
2+| PostgreSQL version 13.11


|===